### ISSUE TITLE
Find top k classes that are most similar to a given visualization

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#105]
We plan to start with a simple algorithm, which makes the following assumptions.
- selected X and Y attributes will have no constraints.
- every other attribute can have a maximum of one constraint.
- euclidean distance based similarity
- line charts only

Flow:
Users will draw the desired visualization (sketch), click "Submit", the backend will send back top k (10 by default) visualizations with x, y, and constraints metadata. At the front-end, we need to show to the users any meta-data (constraints for example) being sent back with the output visualizations.

**Comment by superchaoran** [comment]
This might be an interesting paper to look at[Discovering Structure in High-Dimensional Data
Through Correlation Explanation](https://arxiv.org/pdf/1406.1222.pdf)

**Comment by adityagp** [comment]
Very interesting paper, Chao!

**Comment by superchaoran** [comment]
@adityagp Sorry the paper I found was a bit outdated for current trend. This one might be better:

**Comment by superchaoran** [comment]
We can view our data points as image inputs if they are dense enough, then we can use GAN to train and have features and patterns identified.Interesting part would be what is the high dimensional data cube has very sparse data points.
