### ISSUE TITLE
Migrate file based schema management to postgres metatables.

### ISSUE THREAD

**Issue by superchaoran** [zenvisage/zenvisage#109]
1. We still need to use the wrapper type class for the arbitrary type of x,y,z list. 
2. But for the construction of the class,  we should get the type from metatable and use that instead of regex. 
3. Regex conversion method can be saved/commented out for in future elimination of schema file upload process.

**Comment by adityagp** [comment]
Huh? the topic and content seem to be very different @siddta @superchaoran can you clarify?

**Comment by siddta** [comment]
If we move to the metatable, we can store the types of attributes directly in the table, so we wouldnt need to use regex.
