### ISSUE TITLE
Dynamic Class Creation enable for x,y,z attributes

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#129]
Dynamic Class creation should be done on all possible attribute (not just y attributes). Currently, in the class creation table only y attributes are displayed.

**Comment by adityagp** [comment]
This is good to address. @superchaoran can you take a look?

**Comment by adityagp** [comment]
@superchaoran will take a look

**Comment by adityagp** [comment]
@dorisjlee can this be addressed at the frontend?

**Comment by dorisjlee** [comment]
Addressed in commit [caa7e24](https://github.com/zenvisage/zenvisage/commit/caa7e24e3236c713ab23639c913ef3405c02f146).
Here is a demo of how dynamic class could be created on an x axis attribute (month)
![image](https://user-images.githubusercontent.com/5554675/31252808-09d23f8c-a9e8-11e7-943f-7dbc633c8a1a.png)
