### ISSUE TITLE
Eliminate display of -1 classes for dynamic class results

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#130]
Do not display classes with no data satisfying that condition(i.e. class value shown as negative classes) from showing up.
Example with astro dataset : 
![image](https://user-images.githubusercontent.com/5554675/29502943-62639b4a-85f9-11e7-9dba-549d8bfd24af.png)

[min, 6.0], [6.0, max]
[min, 18.0], [18.0, 20.0], [20.0, max]

![image](https://user-images.githubusercontent.com/5554675/29502947-7049ccde-85f9-11e7-938c-58a41fa24d1f.png)

![image](https://user-images.githubusercontent.com/5554675/29502911-3971812a-85f9-11e7-8005-aab0f55b48b8.png)

**Comment by adityagp** [comment]
@superchaoran Can you take a look while you're taking a look at #129

**Comment by adityagp** [comment]
@dorisjlee will investigate this and provide more info to see if this can be fixed at the frontend

**Comment by dorisjlee** [comment]
Addressed by commit [ed4bbd9](https://github.com/zenvisage/zenvisage/commit/ed4bbd9dcf244fca9a8be19571dedc03ff56c7b1)

**Comment by adityagp** [comment]
Thanks @dorisjlee!
