### ISSUE TITLE
Limiting scrollbar range for results panel

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#132]
The query results scrollbar should be limited the page width so that one could scroll through the results (not via the master scroll bar for the whole page). This is a bug because currently visualization at the bottom of the page can not be dragged and dropped onto canvas without pressing the UP button and dragging up at the same time.
![image](https://user-images.githubusercontent.com/5554675/29503090-8286dda0-85fa-11e7-9ecc-c66970fcdc50.png)

**Comment by adityagp** [comment]
This is an important usability bug to fix. @zzhng107 can you take a look?

**Comment by dorisjlee** [comment]
This is now  resolved by commit [6af574bc](https://github.com/zenvisage/zenvisage/commit/6af574bc2142a7fd920a06900f3ad6691a34ca10) and [48edf75](https://github.com/zenvisage/zenvisage/commit/48edf7552fafe4650a7f1a616dce550f398cf9b2).

**Comment by adityagp** [comment]
Excellent -- thanks @dorisjlee!
