### ISSUE TITLE
Drag and drop display issue

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#133]
When dragging and dropping representative and outlier, the visualization doesn't show up if it crosses the settings panel. @siddta suggest that we might need to change the z-value in the CSS which determine the relative order of elements.
![image](https://user-images.githubusercontent.com/5554675/29503143-cf5a07f6-85fa-11e7-8e7f-e98fb849fcd3.png)

**Comment by jaywoo123** [comment]
fixed with 'appendTo: body' attribute of draggable ui

**Comment by dorisjlee** [comment]
[Link to commit 3d88f02](https://github.com/zenvisage/zenvisage/commit/3d88f02bc1e601e8c04234d42842aef44a0ed431)
Thanks @jaywoo123 !
