### ISSUE TITLE
Stop rerendering outliers and representative every time a query is fired

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#134]
We only need to recompute outliers and representative when we change smoothing or filtering constraint. Other times when we simply do simmilarity search, it is unecessary to resubmit the outlier and representative patterns  to the backend.

Fixing this bug requires some knowledge of how angular JS works. @jaywoo123 has taken look at this issue previously.

**Comment by jaywoo123** [comment]
Pushed changes that fix recomputation. Needs to be tested though.

**Comment by adityagp** [comment]
Any update on this? Related to #161 ? @eidehua @dorisjlee

**Comment by dorisjlee** [comment]
I think backend is no longer calling outlier and representatives now, based on looking at frontend behaviour and also backend logs.

**Comment by adityagp** [comment]
Super!
