### ISSUE TITLE
Plan for user study

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#14]
Yahoo
Prof. Venkat at CMU
Other options? Next steps?

**Comment by adityagp** [comment]
I reached out to Venkat. Hoping @wookhuk and/or @seanzyx can join in the discussion as well.

**Comment by wookhuk** [comment]
I have reached out to prof. Chang. Will most likely talk to him on campus about the details when I get back.

**Comment by siddta** [comment]
@wookhuk : What's our roadmap for the next few weeks on this? Sorry, I haven't been up-to-date on this.
