### ISSUE TITLE
Uploaded data and schema files should not be stored in target folder

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#140]
-- On rebuilding these files get erased, causing getformdata error at the front-end. Users currently need to re-upload the files with a new dataset name.

To resolve this,
--  Save files in a src/main/resources folder. @jaywoo123 tried this, but I guess saw some path related issues.
-- ideally, all schema details should be read out of database metatables.

**Comment by siddta** [comment]
@jaywoo123 has this been already fixed? I think it is.

**Comment by jaywoo123** [comment]
Yes, I just tried uploading a dataset and rebuilding. I did not get any formdata error. If you see this problem again, let me know.
