### ISSUE TITLE
Dynamic class schema file manual addition

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#143]
Currently for dynamic_class to be displayed as a category axis, we need to manually add in the line 
``dynamic_class:string,indexed,F,F,T,F,F,0,Q`` after data upload into the schema file. This should be changed and done automatically.

**Comment by adityagp** [comment]
Is this still necessary? Also related to issue #151

**Comment by adityagp** [comment]
Merged with #151
