### ISSUE TITLE
Zenvisage doesn't work when postgres runs on a different port 

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#145]
Change README instruction. By default postgres runs on port 5432, if this is changed if another address is busy, then Zenvisage can not detect where postgres is running and can give port not found or permission denied error.

**Comment by siddta** [comment]
@zzhng107 when you have time could you please extract postgres port out into the config file from the SQLQueryExecutor class? That way we can run postgres on a different port, and simultaneously modify the config file.

**Comment by adityagp** [comment]
thx @zzhng107
