### ISSUE TITLE
Query comparison green plot doesn't show up for latter x axis values

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#148]
In the green query comparison plot in the results panel, the query visualization doesn't show up for larger values of x. 
![image](https://user-images.githubusercontent.com/5554675/30035845-dd914634-9173-11e7-8d9c-5a70b3a6108d.png)

**Comment by adityagp** [comment]
I figured out one scenario when this happens (now can replicate). If you have dragged a chart with a smaller x-axis at any point, all future ones will only show the chart up until the smaller x-axis end-point.

**Comment by adityagp** [comment]
My hypothesis is not correct. This happens even when the x-axis is the same across visualizations.

<img width="241" alt="screen shot 2017-10-02 at 4 13 27 pm" src="https://user-images.githubusercontent.com/1056605/31099773-c3eb1dac-a78c-11e7-8e0e-be411fa0e689.png">

**Comment by jaywoo123** [comment]
fixed
