### ISSUE TITLE
Plan for version 1.0 release

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#15]
We need to decide on the date, and other things.

**Comment by adityagp** [comment]
Let's aim for July 1, with the first "fully" working implementation of all interactions on the zenvisage frontend, with a separate ZQL based frontend. 

This will require:

Frontend changes:
a) Removing bugs on front-end
b) Cleaning up js code and redundant functionality
c) Commenting as much as we can
d) Import of a file support
e) Installation instructions updated
f) Sean's current code for similarity search (or simpler) added to the main code base

ZQL changes
a) Gary's code to be integrated and supported separately
b) Installation instructions for Gary's code and separate front-end
 
Others: @wookhuk @eidehua @garyluoex @seanzyx @siddta : do you guys think this is a complete list for our first release? Maybe we can come up with a list of tasks after that.

**Comment by wookhuk** [comment]
I think this is a good list. I think one more thing to add is some backend and API call changes that needs to happen due to addition of the new sketchpad library. I should be able to list out what exactly I need pretty soon. Not sure how much fixing is needed in the backend but I'm not expecting major changes from my brief research.

**Comment by adityagp** [comment]
OK good. Can you let us know soon so that we can break this list + your additions down into tasks that we can assign? Until then @siddta do you want to make sure each of the tasks above are reflected as issues and assigned the July 1 milestone or earlier? Thanks.

**Comment by siddta** [comment]
For the first release, I created a couple of issues. Does July 18th sound good for the release?

**Comment by adityagp** [comment]
July 18th sounds fine. Are the tasks you assigned exhaustive relative to what I had listed above, @siddta

**Comment by siddta** [comment]
I think we had fixed majority of the above listed items, will check and add to the todo list if we are missing anything.

**Comment by siddta** [comment]
@adityagp: Given that our uploader seems to be working well,  I think we can have our V1.0 release as soon as we are done with some of the changes in the backend namely -- interpolation, option for unindexed z values, option for non-aggregated Y values. 
We can prioritize these changes as well if you think they are necessary for V1.0:
1) option for binning
2) scatter plot and barcharts
3) postgres support for extremely large datasets.
3) a little of ZQL (link to the separate interface or it's easy to add the table into the new interface also).

**Comment by adityagp** [comment]
I think this is a good list. The question is how much additional work beyond the user study-related work would be needed to get this "out". If it can be done along the way, I would be super keen to release this. I don't think binning/interpolation is essential for V1. 
2) is not essential either, but would significantly distinguish us from other papers on query by sketch.
The q is whether other user study participants need either barcharts or scatterplots @wookhuk ?
3) is essential for a release
I think this is probably also relevant for the user study, especially for the "big data" users like Yahoo or Turn.
4) is essential for a release
I think this is probably not essential for the user study, so the q is how much additional effort is needed for this.

I would be very happy if we can cite the open source release in the CIDR paper when we submit.

**Comment by siddta** [comment]
yes, I think 3 and are important. For 4, should we add the table to the main interface as an option  (visible only on some button click) for consistency?  
I feel If we could do 2 even if it's pretty basic, that would be great.

For the CIDR paper citation, we could add the links to the website and github if it's allowed. It might be a bit tight call for us to able to annouce it as opensourced by then since some of zql based backend is still under development (though it would be fully functional by the time we demo or submit camera copy in case it's accepted).

**Comment by adityagp** [comment]
Re: CIDR paper citation, that's fine. How about we aim to get the best current version out by September 1? I suspect many of the issues will be dealt with for the user study anyway. I propose that we don't try to do anything additional -- highest priority items are VLDB paper, user study, CIDR paper, code release, in that order.

**Comment by siddta** [comment]
Sure, sounds good.

**Comment by adityagp** [comment]
Closing: all of these are already handled, for the others I will initiate new issues.
