### ISSUE TITLE
docker not able to run zenvisage

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#150]
Docker build is successful, but fails to run the service. Maybe because postgres start was unsuccessful.

Error:
ubuntu@zenvisage:~/zenvisage$ sudo  docker run --name zenv1 -d -p 8080:8080 zenvisage

ubuntu@zenvisage:~/zenvisage$ sudo  docker logs zenv
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by adityagp** [comment]
Is this still an issue? @jaywoo123 did you figure out why @siddta's deployment didn't work?

**Comment by siddta** [comment]
It seems docker fails to start postgres on the knoweng server. Possibly the command used in docker script to start postgres may not work for the specific version on postgres installed on that server. There are several variations of the start-up command; and not the same command might always work. 
So in order to verify this; we could do the following:
a)  run the command used in the docker script manually to validate it doesn't work.
b) If a) is true; find the right command, test it manually, and then update the docker script.
c) Update the wiki, or maintain two versions of docker script for different versions of postgres.

**Comment by adityagp** [comment]
This is a good long-term strategy, but I thought @jaywoo123 was going to document this as a known bug for now.

**Comment by dorisjlee** [comment]
Resolved in Issue #206
