### ISSUE TITLE
Support comparisons across x, y, and z attributes using sketching panel.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#154]
To start with, we can support two new features to make this easier:
a) do not erase the sketching canvas on switching attributes.
b) can we copy the viz in a buffer and paste it in the canvas as we switch attributes.
c) we could perhaps also have "add to cart" functionality to store multiple visualizations in the buffer, and use them later on in the exploration for similarity/dissimilarity matching.

Could also be a first step in making multistep queries through the interface.

**Comment by adityagp** [comment]
The ability to "star" visualizations to see them later, or record some form of history is a very natural idea. You're proposing going beyond that; when would we want to remember a viz "shape" for a future query?

**Comment by siddta** [comment]
This is related to the visual primitives I was mentioning earlier, can explain more when we meet.
