### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#155]
Maybe @zzhng107 can update how he is planning to implement, or can wait until we meet.

**Comment by adityagp** [comment]
@zzhng107: please report on talking to mangesh and paul

**Comment by siddta** [comment]
Hey @zzhng107 let me know when you plan to meet mangesh and paul; I'd like to join as well.

**Comment by zzhng107** [comment]
@siddta I chatted with Paul shortly through slack and I think I'll give a try by myself and let you guys know how it goes.

**Comment by zzhng107** [comment]
- [Done] Users tables set up
- [Done] Hardcoded login request from frontend to backend
- [Done] Login request through connection to users table
- [In progress] Simple Hash function
- [ ] Another table for users-tables mapping
- [ ] Reaction after successful login
        - [ ] Return table list based on authentification
        - [ ] Cookies and expiration
- [ ] Insert query into users table (Registration)
- [ ] Insert query into user-tables table (Uploading)

**Comment by zzhng107** [comment]
- Users now can fetch their own tables if associated with their authentification. 
- Authentification is done using a cryptographically-random salt. For more information, check it out here [https://github.com/defuse/password-hashing](url)
- Users and user-tables pair information are manually stored for now. 
- Uploading datasets with authentification is not supported yet. 
- Registration is not supported yet. 
- Cookies and expiration is not implemented

**Comment by zzhng107** [comment]
- Uploading datasets with authentification is supported now.
- Registration is supported now.
- Cookies and expiration are implemented.
