### ISSUE TITLE
startup popup 

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#157]
When the user starts up Zenvisage, they should get a popup directing them to the tutorial and some basic intro blurb about Zenvisage. In that popup we should also have an option to "Don't show me this again" for users that are familiar with zenvisage.

**Comment by jaywoo123** [comment]
testing on other devices is needed as the 'dont show me again' button uses variables local to device.

**Comment by jaywoo123** [comment]
done
