### ISSUE TITLE
Selecting student dataset returns a "/getformdata error"

### ISSUE THREAD

**Issue by eidehua** [zenvisage/zenvisage#16]
Backend throws a NullPointerException, did we get rid of this dataset?

**Comment by adityagp** [comment]
Not that I know of, @siddta ?

**Comment by siddta** [comment]
This is because we don't load the student dataset anymore at the backend. Look at src/main/java/edu/uiuc/zenvisage/service/ZvMain.java.  It was manually created dataset and wasn't serving any purpose. @eidehua if you need it, we could it back.

**Comment by eidehua** [comment]
I don't need it, so we should probably remove the frontend selectors for the student dataset right?

**Comment by wookhuk** [comment]
@eidehua yeah just go ahead and remove!

**Comment by eidehua** [comment]
Fixed with 
https://github.com/zenvisage/zenvisage/commit/34249e89505d7a0219bb30f23d49695c242befe6
