### ISSUE TITLE
Backend called twice during drag and drop

### ISSUE THREAD

**Issue by eidehua** [zenvisage/zenvisage#161]
When you are on the network tab in developer tools, it shows postSimilarity and getClassInfo are called twice. When you do a sketch change it just does it once, so I believe this is a bug.

![pasted image at 2017_09_22 03_58 pm](https://user-images.githubusercontent.com/7684873/30770508-444c4ad0-9ff8-11e7-844f-ba47ac3d7777.png)

**Comment by siddta** [comment]
I have observed this before as well; even for representative / outliers front-end  seems to be making more than one calls for the same query. This problem gets further aggravated when users make changes to parameters (e.g. smoothing) in quick succession, ultimately resulting in many connections to postgres, and sometimes crashing it (we've another issue for this).

**Comment by jaywoo123** [comment]
Confident that this is fixed. Please check if the behavior is correct. This was caused due to minor bug in "brushed" function of draw.js which triggered getUserQueryResults one more time.

**Comment by adityagp** [comment]
@eidehua can you check to see if the fix addresses the issue?

**Comment by eidehua** [comment]
Confirmed fixed
