### ISSUE TITLE
Example ZQL queries should be associated with dataset information

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#162]
Right now, it reads as Q1, Q2, ... I wasn't sure whether the query was applicable to the dataset I was playing around with. 

A simple improvement to make it clear which dataset they belong to would be Q1(Real Estate) Q2(...) Q3(Airline) etc.

**Comment by eidehua** [comment]
Here's my solution to it from 7a70ba09e4d3883009149952b92c89a430a9adb6
![image](https://user-images.githubusercontent.com/7684873/31066173-93580d66-a710-11e7-90aa-4bb3f993a3d2.png)

Though probably there should be a better longer term solution

**Comment by adityagp** [comment]
Looks good to me!
