### ISSUE TITLE
Wiki needs to be better organized and more complete

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#163]
Wiki needs to have a central page that talks about installation instructions, instructions on how to use ZQL, instructions on how to use other features.

**Comment by adityagp** [comment]
@dorisjlee do you want to take a stab at this? A quick start guide like [ this ](https://github.com/dataspread/dataspread-web/wiki/Quick-Start-Guide) is a nice way to introduce all of the features of the tool, and the user guide like [ this ](https://github.com/dataspread/dataspread-web/wiki/User-Guide) is also valuable. Maybe both guides aren't needed in the zenvisage context, but we should describe what the various system options mean. Happy to edit once you've made a first pass.

**Comment by dorisjlee** [comment]
Yeah, I'll work on it, its on my to-do.
