### ISSUE TITLE
Weirdness when two tabs are open with zenvisage

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#165]
Parameters from one seem to transfer onto another. I opened two zenvisage tabs, one where I did smoothing -- those parameters moved to the other tab as well.

**Comment by siddta** [comment]
Possibly because code is shared across the tabs in browsers, and we might be using global/shared variables in the front-end to maintain the state.

**Comment by dorisjlee** [comment]
I've just tested this locally with 3 tabs and operating on 3 different datasets, changed various parameters (including smoothing), and it seemed to work fine.

**Comment by siddta** [comment]
@adityagp which browser did you use? It doesn't work correctly on Safari, and maybe on firefox too.

**Comment by adityagp** [comment]
I had this happen with two tabs on Chrome. I did open one tab a bit later (say 10 minutes) than the first, and then when I came back to the first, I found that some of the settings had carried over. If this is not repeatable, we can hope it doesn't happen and close this issue.

**Comment by siddta** [comment]
I also couldn't replicate this on chrome either, maybe there is a bug which gets triggered off on certain interactions.

**Comment by adityagp** [comment]
closed until we can reproduce
