### ISSUE TITLE
Show scatter should make representative and outliers also show datapoints

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#170]
![screen shot 2017-09-27 at 3 41 08 pm](https://user-images.githubusercontent.com/5554675/30936718-58840dee-a39a-11e7-94f6-4fe3a03eb2fd.png)

**Comment by adityagp** [comment]
@jaywoo123  will take a look post his midterm

**Comment by jaywoo123** [comment]
closing this because scatter plots are now re-generated
