### ISSUE TITLE
Move the decision on whether to log the interactions and queries to the backend

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#173]
Currently it's done at the front-end inside index.html at the very bottom:
 “var loggerOn=true”

Front-end should always send, backend logs or not based on a flag stored in the config file.

**Comment by adityagp** [comment]
Good find. (btw, I can't parse the second sentence.) I agree that logs should aways be sent to the backend, and back-end should decide whether to log or not.

**Comment by siddta** [comment]
Made the second sentence more clear.

**Comment by adityagp** [comment]
agreed!

**Comment by adityagp** [comment]
@zzhng107 will add as config parameter
