### ISSUE TITLE
DatasetController gets created 5 times

### ISSUE THREAD

**Issue by eidehua** [zenvisage/zenvisage#175]
I just added a console log to the datasetController. On just loading the page, it gets created 5 times. Any ideas?

![image](https://user-images.githubusercontent.com/7684873/31462782-6b45e408-ae93-11e7-9355-cbdf776355fb.png)

**Comment by eidehua** [comment]
So on the front end we have 5 divs that have ng-controller="datasetController"
So it seems like it creates 5 controllers, so there are 5 event listeners. 

Not sure what the proper design change would be

**Comment by eidehua** [comment]
This is bad..
![image](https://user-images.githubusercontent.com/7684873/31463950-7095dde4-ae95-11e7-8b58-9aedabefc655.png)

**Comment by eidehua** [comment]
Wrap downloads in one datasetController instead of each having one
Try removing optionsController, add functionality to datasetController to temporarily fix this bug

Try to have controllers for each purpose and not contain data (move to services/factories)

Long term: change frameworks, figure out what is best

**Comment by eidehua** [comment]
Merging the options controller and dataset controller worked!

**Comment by adityagp** [comment]
awesome!
