### ISSUE TITLE
Important front-end issues we should fix for the first release.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#18]
1. Scatter plot search seems to be not working, we are getting the results from the backend, but the front-end is failing somewhere. (Done)
2. I think we should hide the drop-down menus below the drawing panel when we are not doing pairwise search. It's confusing, users can use the left side for selecting the attributes. (In progress)
3. X and Y axis scales changes on scrolling, I think this is something that is Ed's work in progress, but he had to work on something else. I think we should turn this for the release. (Todo)
4.  We should remove Y attributes from the release estate dataset which are useless. (I will work on this)
5.  Add support for sum based aggregation. (?)
6. Fix multiple calls to the backend. (Making good progress)

These are good for now, we should update this list if we see more. 

@adityagp @eidehua

**Comment by eidehua** [comment]
For two, I am going to do some refactoring. Right now we have separate event listeners for the drop-downs and the left side bar, that both have their own functionality, while they should have the same functionality. 
When doing pair-wise search should I collapse the left-side-bar X and Y axes selectors?

**Comment by siddta** [comment]
Ok, 
Collapsing might be too much work, easiest would be too just in hide the drop-down menus?

**Comment by adityagp** [comment]
@siddta 

re:

1, 2: Yes, we should definitely try to make these changes
3. Do you mean we should turn this ON? Yes I agree, it seems odd without it at least somewhere -- either the central chart or the similarity search charts
4. This doesn't seem like high priority but seems fine if it's easy
5. What do you mean by we should hide it? Aggregation seems quite important.

**Comment by siddta** [comment]
@adityagp 
3: I meant scrolling on the x scale where we kind of zoom in/ zoom out, it doesn't work that well.
5. Backend only does avg based aggregation for now. Instead of removing sum for now, I will add this support to the backend.

**Comment by adityagp** [comment]
I think 5 is important, we should fix that. For 3, I leave it to your judgment.

**Comment by seanzyx** [comment]
3: John is working on the zoom in & zoom out functionality in his version
of zenvisage, we can see how it turn out.

Sean

**Comment by eidehua** [comment]
Pushed a quick fix for number 1. 
Basically, the functionality for scatter search was tied to the small search button, as opposed to the big submit button we have now.

But there is a bigger problem, which is how overloaded the submit button is. This definitely needs to be refactored, there are many places that use onsubmit internally for the dynamic nature of it, but it should understand the chart type and handle different charts differently. I also think there could be some loops or double coding where several of our functions are "submitting" and this causes our console log to basically output several times for dataset changes and submit presses.

**Comment by adityagp** [comment]
I see -- is there a way @wookhuk is dealing with this issue in his version? maybe we can borrow that piece so that we can fix and move on with the first release.

**Comment by eidehua** [comment]
Currently, onSubmit() uses world data (global data) -- since there are no parameters, it must handle every type of chart in a different way. I think refactoring it to onSubmit(params) would be very useful, where we pass in the state information.

Also, we currently are mixing two kinds of "submit" events -- onSubmit() and updateTrends()
updateTrends() does some stuff, then calls onSubmit(), and seems to be used right now as another kind of submission event, that also updates the trends. This should be refactored so updateTrends() only updates the trend.

Another issue in updateTrends would be the asyncronous nature of javascript -- it fires a backend call to update the trends, then later on calls onSubmit(). 
onSubmit() might get to the point where it needs the trends before the backend call finished. 

So the actual issue is no onSubmit being overloaded, it is updateTrends().

**Comment by eidehua** [comment]
It's also pretty confusing to me still, but refactoring updateTrends should be very useful. Also will take some time since so many places use updateTrends / onSubmit

**Comment by eidehua** [comment]
Alright, I made a revamp for updateTrend flow, now we have two functions called updateBothTrends (for pairwise) and updateOneTrend(updating one trend only). Still might be a few minor issues, but almost all the console errors seem to be gone now. 

If someone could review my refactor that would be cool, want to know if the way I refactored is good.
https://github.com/zenvisage/zenvisage/commit/b477dd0c3bfc10e62e8ca7a3ba0b8f3e38dd4113

**Comment by siddta** [comment]
@eidehua Will check your implementation whenever I get time. 

Ed could you please update the above list with their current status. We could also discuss sometime on Monday/Tuesday.

**Comment by adityagp** [comment]
@seanzyx was looking into data upload at some point. 

I am not sure about the scatterplot search (I presume you're talking about www.scattersearch.xyz): I think it's substantially different from the current system, not sharing any frontend or backend elements, so it's probably best to keep it separate for now. How does the vanilla scatterplot search within our current zenvisage implementation look -- I remember @eidehua and others looking into it at some point?

**Comment by siddta** [comment]
Yeah, I meant www.scattersearch.xyz.
the one within zenvisage is much faster, however it's still not too robust, interface can be improved further.  @eidehua: I think you fixed the search issue, did you spot other issues?

**Comment by eidehua** [comment]
Update (I always edited the first post)
1 is done
2 is in progress -- the refactoring i have been doing already is partial to support this too.
3 -- am I to remove this functionality now? This would be part of a generate-vega cleanup/refactor, which I have not done yet
5 - ? 
6 - My revamping a few days ago fixed this issue, but more testing needed.
