### ISSUE TITLE
add "root" user login that has permission to add dataset >100MB limit 

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#189]

**Comment by dorisjlee** [comment]
1) Backend: During table creation, by default create a "root" user (add row to user table, SQL). 
2) Frontend(?): Given them special permission to trespass the file upload limit.
assigned to Xu

**Comment by JosemyDuarte** [comment]
I would like to help with the backend part, beside updating the Readme.md file, what else should be modified?

**Comment by dorisjlee** [comment]
Resolved as part of commit [7c3079d](https://github.com/zenvisage/zenvisage/commit/7c3079d24d61ec5a8baf136a1decc7d430b2440d)
