### ISSUE TITLE
Improve ZQL interface

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#19]
Work on ZQL interface, possibly try to merge the user-study one and the Gary's one. User-study one is more user friendly, if we can easily integrate that with Gary's parser that would be great.

@adityagp

**Comment by adityagp** [comment]
Agreed. Will you be doing this? Chaoran could also look at this but I don't know what plans @wookhuk  has for him. This could be useful for John's interface as well.

**Comment by siddta** [comment]
I was thinking of making some simple UI improvements so that people don't find zql super difficult to use. Maybe Chaoran can look at it after my first pass.

**Comment by siddta** [comment]
Pushed in some changes to make ZQL table updatable (Learnt some angular as well while implementing). Will add more changes this week as and when I get time.
However, I still the ZQL is not too usable. We need to discuss maybe. @adityagp

**Comment by adityagp** [comment]
OK maybe you can do a walkthrough next time we chat?

**Comment by siddta** [comment]
ON HOLD.

**Comment by adityagp** [comment]
Closing for now.
