### ISSUE TITLE
Merge ZQLParser code to the main repo.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#2]
We should merge Gary's code to the main repo when he is done.

It would have:

1. A separate page for ZQL interface (Let's call it zql.html) -- This will replace the current ZQL interface in the page sometime in the future.
 
2. ZQL Parser

3. A new package at the backend  to execute ZQL.

**Comment by siddta** [comment]
For the backend code: create a new package: edu.uiuc.zenvisage.zql1.executor  under src/main/java ( keep edu.uiuc.zenvisage.zql.executor as it is) , and at the front-end - create a new html page: zql.html and add all javascript files need for zql.html under a new folder called 'zql' under src/main/webapp. For postgresql library you need to add a dependency in pom.xml. you can google for maven dependency for postgresql.  ping tarique if you need help.

**Comment by garyluoex** [comment]
added new package edu.uiuc.zenvisage.zqlcomplete.executor
added new zqltable page in webapp/zql*
added POM dependency for postgres

**Comment by adityagp** [comment]
@garyluoex could you provide a short snippet of how you'd use zql within your branch? what are the steps involved in installation, and can you provide a small example? thanks.

cc: @siddta

**Comment by siddta** [comment]
Your code doesn't build. Tthe reason is that the classes you are accessing from other packaages like Query, etc have been moved  to other packages during cleaning. You can fix them easily using eclipse

Always ry running the steps mentioed on git readme file before committing.

**Comment by adityagp** [comment]
Thanks @siddta. @garyluoex could you do this? Seems straightforward.

**Comment by garyluoex** [comment]
@siddta  @adityagp  I fixed the build problems in zqlcomplete, in order to use zqlcomplete with the test zql table /webapp/zql.html we need to add a routing on the new jetty server I believe, I will talk to tarique to see how it can be done.

**Comment by siddta** [comment]
I'll add the routing tonight.

**Comment by siddta** [comment]
@garyluoex: I added a routing with path  /zv/ZQLComplete (look at function executeZQLComplete in zvBasicAPI class). Also updated the app.js file.

However, the request object has to be the json representation of ZQLTable, I'm not sure what $scope.parsed is doing? Gary could you check it? Also how did you test the backend? I dont see any you are visualizing the results in zql.html, could you copy the corresponding code from the main page - index.html. For the javascript code, if you look at xdata.js, you can see what which javascript functions are being called to process the reponse. We need to call the same functions from app.js. Let me know if you need help.

**Comment by garyluoex** [comment]
@siddta  @adityagp 

The problem is due to the "same-origin-policy". you can find more information here <https://en.wikipedia.org/wiki/Same-origin_policy> or here for potential fix <https://developer.chrome.com/extensions/xhr>

So basically simply adding routing for GET request url is not sufficient, we need to add routing to the zql.html page so that it share the same host:port with the request url. Or we can have a temporary fix by adding the cross origin permission.

**Comment by adityagp** [comment]
@garyluoex @siddta What is the status on this?

**Comment by siddta** [comment]
@garyluoex is working on the documentation. Besides that, we can execute the queries mentioned in zqlparserdemo folder .
