### ISSUE TITLE
DTW doesn't seem to work

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#200]
![image](https://user-images.githubusercontent.com/1056605/41683937-b5675e5c-74a1-11e8-90dc-542d47f2a036.png)

**Comment by siddta** [comment]
Move javaml in src/main/resources folder from the lib folder at the root.

**Comment by dorisjlee** [comment]
Tested and resolved in commit e9fcaf and bedcdf. Issue is due to an outdated javaml package. Then run file is also updated so that the required library is copied over every time when we run zenvisage, so that it is not cleared out.
