### ISSUE TITLE
Docker-compose working files in order to run Zenvisage

### ISSUE THREAD

**Issue by ABeltramo** [zenvisage/zenvisage#206]
Hello everyone,

I just saw your project and I wan't to give it a try. Given that the dockerfile present here is not working I reworked a little everything and created a docker-compose file that separates postgres and zenvisage.  
You can checkout my [repo](https://github.com/ABeltramo/zenvisage-docker) to see how it works. Here are a couple of hacky things I had to do in order to set it up:

- Instead of one big docker image with postgres, java and Zenvisage I separated in two docker images: `postgres` and `zenvisage`.
- The `postgres` image is initalizing with the creation of the schema and the table needed by Zenvisage.
- The `zenvisage` image is based on the official [openjdk](https://hub.docker.com/_/openjdk/) image.
- In order to connect `zenvisage` and `postgres` containers I changed the Java files that contains *localhost*.

I hope this will help someone else that, like me, are struggling using docker with this amazing project.

**Comment by siddta** [comment]
Thanks @ABeltramo. This sounds like something we should fix in v3.0. @Renxuanwang.

**Comment by dorisjlee** [comment]
Thanks for the contribution @ABeltramo. @Renxuanwang and I have tested this on Mac and Ubuntu and incorporated this into our repo, in commit [fa9a992](https://github.com/zenvisage/zenvisage/commit/fa9a992e79c6e71615d4ed7aca8c931d262b263d) and [59bd3a](https://github.com/zenvisage/zenvisage/commit/59bd3ab1764730fe4e9f64f05d73d4d55dfcdada).
I've also updated the wiki with the new set of instructions for Docker installation.
