### ISSUE TITLE
Add query executor support for postgres

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#24]
Making query executor within zenvisage more robust.

https://docs.google.com/document/d/1nWHEu-k8BhM1-Ddh5xE-fdp2c6n9o4hB_7yr_J2kAy8/edit

**Comment by superchaoran** [comment]
i tested local postgres, queries worked well. Looks like the original SQLQuery.java is well written even with conversion from ZQL table.

**Comment by superchaoran** [comment]
Next step im going to test import csv to postgres.
![image](https://cloud.githubusercontent.com/assets/7088689/16975815/a385c832-4e0f-11e6-9817-6fe64e1a6bb7.png)
Then use SQLQuery.java to build a query string and use SQLQueryExecutor.java to execute it to see result.
Something like Select Z,X, avg(Y) from table where T=t1   group by Z, X order by Z, X.

**Comment by siddta** [comment]
How are we storing the output of sql query? Earlier we were using linkedhasmap of linkedhashmap. I'd propose we create a class now.  Something on these lines:

Class VisualGroups{
    ArrayList<VisualGroup> visualGroups;  
    ArrayList<String> zValues;
}

Class VisualGroup{
   ArrayList<String> X;
   ArrayList<String> Y
}

**Comment by siddta** [comment]
For the data upload, we can do something simple: 
we ask for a schema file like this:
tablename,
attributename1, type, category
attributename1, type, category
attributename1, type, category

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/16994107/9975a086-4e6b-11e6-9b4b-ae11fe7a36bd.png)
The existing code use inMemoryDatabase for each table, then load them into

**Comment by superchaoran** [comment]
We need to change the Executor getData to postgres calls.
![image](https://cloud.githubusercontent.com/assets/7088689/16994739/4e635ed2-4e6e-11e6-87ae-ea7b71a7ea84.png)

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/16994805/9b3a7132-4e6e-11e6-82a2-9eccac14bcb9.png)
By changing it we can link it up.

**Comment by superchaoran** [comment]
return of SQL would be cater to ExecutorResult
![image](https://cloud.githubusercontent.com/assets/7088689/16994916/17bcb9fe-4e6f-11e6-9d92-460fd9e7bb80.png)

**Comment by siddta** [comment]
@superchaoran : any updates?

**Comment by adityagp** [comment]
@superchaoran what's the status on this? Seems like the API call should look the same independent of in-mem or SQL implementation.

**Comment by siddta** [comment]
@superchaoran was busy with his stats exam last week, could you please add the details of yourchanges here.

Also, we would like to add another layer for doing interpolation/binning etc as part of query executor. Recall my diagram I posted on slack a few days back. There are two ways we can add this change, let me know which one is better:

Option 1: 
Add another step to the executor before returning visualgroups. Query executor should return two types of results:
1) original data as returned by the db (to be return to the front-end for top k Zs).
2) formatted data -- after applying interpolation/binning etc on the orginal data. This data would be passed to the analytics. Formatted data will be called visualgroups.

Option 2:
Instead of  2  as another layer in query executor, we could also take it out and call it data transformation layer which takes visualgroups (output of query exectuor, I think Chao has already implemented this part) as input and return transformed/reduced visualgroups.

I need to spend some more time thinking on this.  @superchaoran and @seanzyx we should probably  brainstorm on this early next week, it intersects with some of the work @seanzyx did recently.

**Comment by adityagp** [comment]
These two options are not very clear to me. Maybe we can discuss in person.

**Comment by superchaoran** [comment]
fixed with commit: 9167ce411a61a121a99078d44ecaad3b9eaf64e3
