### ISSUE TITLE
Add xlabel to the graphs

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#29]

**Comment by siddta** [comment]
Is the xlabel being populated by the backend?

**Comment by siddta** [comment]
Do we show the axis labels now?

**Comment by siddta** [comment]
@wookhuk I still don't see the axes values in the output results?

**Comment by adityagp** [comment]
This is probably high priority -- I can see that participants may worry about getting deceived because the values are not provided.
