### ISSUE TITLE
Confusing code in DTWDistance.java

### ISSUE THREAD

**Issue by seanzyx** [zenvisage/zenvisage#3]
for (int i = 0; i < src.length; i++) {
			double [] point = new double[1];
			point[0] = src[i];
			TimeSeriesPoint tp = new TimeSeriesPoint(point);
			if (i == 0) {
				ts1.addLast(i, tp);
			}
			else {
				ts1.addLast(i, tp);
			}
		}

The if statement is kind of confusing -- it seems to be doing the same thing whether i is 0 or not?

**Comment by siddta** [comment]
Yeah, you're right. Could you please fix it and commit.
