### ISSUE TITLE
Graphs should be able to handle datetime values

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#30]

**Comment by wookhuk** [comment]
Frontend can handle all the datetime values. There needs to be some additional change in the backend. Namely when passing back the data, it needs to include

1. If there is a datetime value in one of the columns
2. If 1) is true, which column is the datetime value

**Comment by siddta** [comment]
@wookhuk @seanzyx : we need to discuss this.

**Comment by siddta** [comment]
Hey @wookhuk, what strategy are we following on this? I think we discussed a couple of them. Are we going ahead with the one where dygraph interpolates the values on drilling down?

**Comment by wookhuk** [comment]
@siddta 
The current setup will use the default datetime handling by dygraphs.

http://dygraphs.com/gallery/#g/range-selector

I think this is quite well done.

**Comment by adityagp** [comment]
i am assuming @wookhuk that this dealt with? if so, go ahead and close the issue.
