### ISSUE TITLE
Allow users to set hard error bounds. 

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#32]
Allow users to set an error band. Something like [this](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwi636WOqI_OAhVI94MKHTbQCpIQjRwIBw&url=http%3A%2F%2Fnmarinsek.com%2Ftutorial-how-to-make-shaded-error-bands-in-excel%2F&bvm=bv.127984354,d.amc&psig=AFQjCNGJAaPqADutNhRz4aaV68GCYNcsgA&ust=1469560045949373). It should prevent the system from returning any results that include points outside the error bound. The size of the error bound should be customizable.

**Comment by siddta** [comment]
I don't think this should be on top of our priority list. But it's good to implement it sometime later maybe after the deadlines. Is it an ask from the participants ?

**Comment by siddta** [comment]
ON HOLD.

**Comment by adityagp** [comment]
Closing this since Dynamic Classes + Error Bars captures this.
