### ISSUE TITLE
Allow users to generate model trends based on existing functions

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#34]
This can come in useful if the users want to compare their data with "theoretical" values and see how much their test data deviates from it. But I would consider this low priority. There is even a work around where the user can input a model trend data as one of the timeseries.

**Comment by siddta** [comment]
Is this part of the user-study? Or a general request.

**Comment by siddta** [comment]
On HOLD.

**Comment by adityagp** [comment]
Done, given equation support.
