### ISSUE TITLE
Bug: CMU Case study data doesn't get response from back-end

### ISSUE THREAD

**Issue by superchaoran** [zenvisage/zenvisage#35]

**Comment by superchaoran** [comment]
RealEstate Input query:{"method":"SimilaritySearch","xAxis":"Quarter","yAxis":"SoldPrice","groupBy":"Metro","aggrFunc":"avg","aggrVar":"SoldPrice","outlierCount":"50","dataX":[],"dataY":[],"yMax":null,"yMin":null,"sketchPoints":[{"points":[

**Comment by superchaoran** [comment]
CMU Input query:{"method":"RepresentativeTrends","xAxis":"vis","yAxis":"vis","groupBy":"id","aggrFunc":"avg","aggrVar":"vis","outlierCount":"50","dataX":[],"dataY":[],"yMax":null,"yMin":null,"sketchPoints":[{"points":[

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/17234502/3fd9538e-54ff-11e6-99b9-206b1a89d8bd.png)
![image](https://cloud.githubusercontent.com/assets/7088689/17234507/4c876e54-54ff-11e6-940a-40a4ac3d7f53.png)

**Comment by superchaoran** [comment]
Selecting class && h20 cause array out of bound error.

**Comment by superchaoran** [comment]
Input Query's x-axis and y-axis are both weirdly "vis" all the time

**Comment by superchaoran** [comment]
i think 
![image](https://cloud.githubusercontent.com/assets/7088689/17234714/fad942b0-5500-11e6-89aa-05f5eef27f5d.png) ExecuteResult is null here

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/17234747/2f1260a2-5501-11e6-832a-97c74c1b45e9.png)
This not not handled correctly somehow

**Comment by superchaoran** [comment]
We should make breakpoints in deeper methods to see why it is returning null.

**Comment by siddta** [comment]
Yes. I suspect the the data we get back from the db is a little different than what the code expects. The best way to debug this is to write a main function or a test class and call zvmain function with the above query. After calling you can debug the code line by line until it breaks.

**Comment by siddta** [comment]
@superchaoran were you able to identify the issue? do we need to talk?

**Comment by wookhuk** [comment]
I second creating a test class to debug this more efficiently. Sean also ran into this problem recently.

**Comment by siddta** [comment]
@superchaoran : were you able to find the issue? Let me know if I need to look into it?

**Comment by superchaoran** [comment]
This was fixed, right? @wookhuk @seanzyx

**Comment by wookhuk** [comment]
fixed.
