### ISSUE TITLE
Fix front end so users input the number of segments for sketchpad

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#36]

**Comment by adityagp** [comment]
Why do we want this functionality? This seems like something we should not leave to the end-user, unless one of the participants explicitly requested for it.

**Comment by siddta** [comment]
Yes, the plan is not to leave this to user. Our default number (dependent upon the length of X axis) would be sufficient for most of the practical cases (recall that our earlier hardcoded 30 segments was not too bad). But just in case, user wants to change it, there should be an option for him to do it.

Thinking of it as an option for increasing or decreasing the resolution/granularity for similarity search, less number of segments means lower resolution, and vice-versa.

**Comment by adityagp** [comment]
Got it: Again, if we want this, this should be hidden away under one of the ?s. What do you think @wookhuk

**Comment by adityagp** [comment]
Again, I am not convinced we want this, so I am inclined to close it. @wookhuk @seanzyx @stevenlcf what do you think?

**Comment by stevenlcf** [comment]
I think it's fine for users to have a high-resolution sketchpad. What's the concern here? Will it reduce the computation? If users want to input a specific pattern, I think they might use the **Input equation** function.

**Comment by adityagp** [comment]
I believe the concern is the computation both from an in-memory processing standpoint and a database SQL processing standpoint.
