### ISSUE TITLE
Fix backend so users can pass in the number of segments as a variable

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#37]

**Comment by siddta** [comment]
@seanzyx : Have time to talk about interpolation and paa implementation today?

**Comment by seanzyx** [comment]
@siddta yeah. your account seems to be disabled on slack? can't reach you.

**Comment by siddta** [comment]
haha, yes. working with @adityagp to resolve this. we should talk at 7pm cst?

**Comment by seanzyx** [comment]
haha sure, let's talk at 7pm cst then
