### ISSUE TITLE
A bug of DTW distance in javaml-0.1.5

### ISSUE THREAD

**Issue by stevenlcf** [zenvisage/zenvisage#38]
I found a bug in **net.sf.javaml.distance.fastdtw.dtw.DTW** (javaml-0.1.5) which is used in **edu.uiuc.zenvisage.service.distance.DTWDistance**

The library class uses the square of Euclidean distance, which actually should be Euclidean distance, as the distance between two TimeSeriesPoint.

This bug could lead to different WarpPath results. For example, two warping paths with distance sequences {5, 5} and {1, 8}. `5 + 5 > 1 + 8` but `5^2 + 5^2 < 1^2 + 8^2`.

This bug is fixed in javaml-0.1.7. Maybe we could update the javaml library.

The following codes are the Euclidean distance function in **net.sf.javaml.distance.fastdtw.dtw.DTW** of two library versions.
Decompiled code in javaml-0.1.5
<img width="978" alt="javaml-0 1 5" src="https://cloud.githubusercontent.com/assets/11813034/17278771/5075ce20-572a-11e6-8965-d9c4aed1794a.png">

Decompiled code in javaml-0.1.7
<img width="963" alt="javaml-0 1 7" src="https://cloud.githubusercontent.com/assets/11813034/17278786/f843ebd2-572a-11e6-8df2-0e0642a922f3.png">

**Comment by siddta** [comment]
good find. thanks.

**Comment by adityagp** [comment]
Not high priority. Pushed to post release 2.0

**Comment by dorisjlee** [comment]
Resolved in #200.
