### ISSUE TITLE
ScatterPlot not working on the github version.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#4]

**Comment by siddta** [comment]
The scatter plot query doesn't work in the merged version; I think the reason is - In trendanalysis() in rect.js,  for scatterplot search we use the same query object which we were using for linechart, but for scatterplot, we need ScatterQuery ( see main.js) instead of Query (see main.js).  The backend fails to  parse Query since it's expecting ScatterQuery. I think it was correctly handled before, but something went wrong while merging, could you please look at it, should be a minor change.

**Comment by eidehua** [comment]
Fixed with f0e5612fa432fdec5165e67c59c4bf9621ca5ab2
