### ISSUE TITLE
New Feature 1: Start thinking about comparing among X or Y axis.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#40]
- we will start with the backend changes, if we could do this, it would be super since that would mean we can run a lot of zql queries. currently z based search we do, i assume there maybe some systems that would be doing the same.
- we need to brainstorm how we will let users specify that he wants to find one of the X or Y axis. I'm sure we would have such a use-case from cmu.

**Comment by adityagp** [comment]
Already done with Ed's X1<-* changes.
