### ISSUE TITLE
BACKEND MAJOR CHANGE: Extend VisualComponentProcessor to do binning/interpolation/so on.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#42]
Currently, I assume @superchaoran has basic query executor working which returns VisualGroups. We now need to apply binning/interpolation etc. to these results. The flow would be like this:

DB----->SQLQUERYEXECTOR ------->Binner/Interpolator----------> taskprocessor (sim, rep, etc)
                     <---------Visual Component Processor---------------> 

After this we will work on taskprocessor.

**Comment by superchaoran** [comment]
Attaching @siddta's meeting notes:
[https://docs.google.com/document/d/1nWHEu-k8BhM1-Ddh5xE-fdp2c6n9o4hB_7yr_J2kAy8/edit]
[https://docs.google.com/drawings/d/1jFdKlmFe3-A58EREEYxYZdUJKl8zYWxbUZLHgRkk8hY/edit]
![image](https://cloud.githubusercontent.com/assets/7088689/17538876/2e4aab58-5e6f-11e6-8e61-b4fb1b2c8ed9.png)
DataReformation class -> Transformation class

**Comment by superchaoran** [comment]
We used to have LinkedHashMap<String, LinkedHashMap<Float, Float>> output in https://github.com/zenvisage/zenvisage/blob/878ce1aa18e90efcdfcbb40455947a5da87aab28/src/main/java/edu/uiuc/zenvisage/data/roaringdb/executor/ExecutorResult.java#L15

**Comment by superchaoran** [comment]
VisualComponentList Tested.
![image](https://cloud.githubusercontent.com/assets/7088689/18067189/4aa27546-6e01-11e6-96b3-54d5cb427ff4.png)
Next Step is to add an interface to convert VisualComponentList to in-memory output.

**Comment by superchaoran** [comment]
Fixed with commit: 3cb69b929805891e912dd5ab46eebfdd78e4631b
