### ISSUE TITLE
Propose a plan on how we're going to manage the new code for John's Interface at the front-end

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#5]
We want to add all the required changes to the current backend in the main branch. So, a new branch is not desirable. 

There are several options (list is not exhausitive)
- create a new page say zenvisage.html in the same webapp folder. Add all new js/css files under a new folder. 
-  create a new webapp folder (not sure if maven will allow it)

**Comment by adityagp** [comment]
I prefer that @wookhuk work within the ecosystem reusing and cleaning up as much as he can. 

If that strategy doesn't work, we can talk about alternatives. @wookhuk what do you think?

**Comment by wookhuk** [comment]
@adityagp We will most likely use a subset of features for the CHI user studies. I will try to make the code as modular as possible so it is easy to merge the current existing functionalities (excluded from the study) back to the zenvisage.html that @siddta suggested. I think either way there will be major reconstruction in the frontend.

**Comment by adityagp** [comment]
Makes sense, thanks. We'll keep this issue open until you poke around and figure out the right location for integration.

**Comment by siddta** [comment]
Looks like we are good here. I am opening a new issue for John to add all apis he needs for updating the front-end. We should have a lot of simpler apis at the backend rather than front-end having to search for specfic things in a large chunk of data returned by one api.
