### ISSUE TITLE
Add explanation in the frontend for the algorithms being used

### ISSUE THREAD

**Issue by wookhuk** [zenvisage/zenvisage#50]
especially for the custom ones.

**Comment by wookhuk** [comment]
@seanzyx 
@stevenlcf 
Please add a description of how your algorithm works here! I can add it to the frontend for the users to see.

**Comment by stevenlcf** [comment]
I'm not sure how long the description should be. Therefore I post two versions here. If they are not suitable, please let me know!
### version 1
MVIP means Matching Visually Important Points. It takes following steps to calculate the distance between two time series:

Step 1: Use z-score to normalize and moving average to denoise the time series.
Step 2: Use perceptually important point identification algorithm to reduce the dimensions of time series and preserve the coarse trends.
Step 3: Use a feature vector to describe each important point selected in step 2. (Currently, a feature vector has 8 dimensions to describe the location, nearby shape and nearby pattern)
Step 4: Use DTW to calculate the distance between two feature vector sequences, which represent two time series.
***
### version 2
MVIP means Matching Visually Important Points. After normalizing and denoising the raw time series, it selects a few important points which preserve the coarse trends, uses feature vectors to describe the properties of important points and uses DTW algorithm to calculate the distance between two feature vector sequences.

**Comment by adityagp** [comment]
Super short + intuitive explanation is better, with no jargon! One sentence at the most.

**Comment by stevenlcf** [comment]
MVIP tries to match visually important points, which depict the coarse trends, of two time series and uses the mismatch score as the distance.

**Comment by seanzyx** [comment]
Segmentation: Summarizes a trend into major line segments and calculates
the similarity based on the matching of the segments.

**Comment by adityagp** [comment]
Both of these are good but are they on the system? @seanzyx @stevenlcf

**Comment by stevenlcf** [comment]
Yes, and I also implemented k-shape's metric, SBD (SBD isn't provided in the interface but it's easy to add it). Users can use them for similarity search now.
One possible problem is that zenvisage removes z-score normalization now which might affect the results.

**Comment by jaywoo123** [comment]
<img width="717" alt="screen shot 2017-09-24 at 12 42 51 am" src="https://user-images.githubusercontent.com/26175962/30779855-246c2bc0-a0c2-11e7-8d97-8d84084eaf7d.png">

Unfortunately, these ? that I added add indentations. If I extend the containers of the headers, the headers may not be visible in 13 inch computers. Are there possible abbreviations that we can use for the long headers?

**Comment by adityagp** [comment]
closing this based on #159
