### ISSUE TITLE
Direct upload files into postgres

### ISSUE THREAD

**Issue by superchaoran** [zenvisage/zenvisage#59]
Saving Sean's upload files into postgres database server as Prof. Aditya suggested on Aug 9th meeting.

**Comment by superchaoran** [comment]
1.file->zenvisage_metatable; 2. file->zenvisage_metafilelocation; 3. file->creatNewDatasetTable; 4. copy file->NewDatasetTable;

**Comment by superchaoran** [comment]
Front-end is hard coded for file upload: need to me changed  <select class="form-control" ng-change="onDatasetChange()" ng-model="selectedDataset" id="dataset-form-control">
          <option value="real_estate">Real Estate</option>
          <option value="cmu">cmu</option>
          <option value="cmutesting">cmu testing</option>
          <option value="sales">sales</option>
        </select>

**Comment by superchaoran** [comment]
This week, spent 23 hours on file upload function:
Managed to get it halfway done.
Things done this week:
1.file->zenvisage_metatable; 2. file->zenvisage_metafilelocation;
Current data set now pull from (zenvisage_metatable, zenvisage_metafilelocation and ZQL load)
Things to be done next week:
3. file->creatNewDatasetTableScheme; 4. copy file->NewDatasetTable;
Need a pulling from front end to back end for current number of datasets.

**Comment by superchaoran** [comment]
FileUpload architecture:
![image](https://cloud.githubusercontent.com/assets/7088689/19026511/70c1e904-88ec-11e6-84a8-5105608e93ae.png)

**Comment by adityagp** [comment]
Whoa! That arch diagram is really confusing. We should talk about this. I can try to come find you today after a defense in the afternoon that I am attending.

**Comment by superchaoran** [comment]
@adityagp Hi Prof. Aditya. I have an interview with LiveRamp from 3:00pm-4:00pm. I can meet you at 4:30pm ish if that works for you. Thanks!

**Comment by adityagp** [comment]
Sure, I'll come find you in your office around then.

**Comment by superchaoran** [comment]
@adityagp Thanks! I will be at SC 2105 around 4:30pm.

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/19119911/dfc7f626-8ae6-11e6-8fd4-3a0a1de682a7.png)
![image](https://cloud.githubusercontent.com/assets/7088689/19119924/e7e60c8a-8ae6-11e6-974b-a7330730c0a4.png)
![image](https://cloud.githubusercontent.com/assets/7088689/19119931/ef3ac3a4-8ae6-11e6-9037-229e9075fce3.png)

**Comment by superchaoran** [comment]
@adityagp Hi Prof. Aditya, I will explain the new architecture @siddta and I discussed about yesterday to the group at 3:00pm today (our usual meeting time). Thanks

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/19122403/efe48b38-8aef-11e6-91fb-d5fb073ae325.png)

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/19122439/1c26c95e-8af0-11e6-9b65-db12864a04d0.png)

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/19128610/b427e13e-8b09-11e6-895b-d5ff41e857c4.png)

**Comment by adityagp** [comment]
Closing...
