### ISSUE TITLE
Clean-up the current front-end code

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#6]
Structure/Modularize it and clean up the redundant/unused code.

**Comment by siddta** [comment]
Ed: I think you can take a shot at it since you understand the most of it, assigned this ticket to you. We are currently not trying to do anything major in the main front-end code, so we can do a good amount of clean-up. You can touch any code other than:
- zql.html and js files under zql folder
- files/folder with word chi in it.

See if you could do the following:
- Angularize the structure and communication between the different pieces. 
- index.html page has too much javascript code, organize them in javascript files.
- Remove any code we don't use.
- Remove redundant code in various javascript functions, add functions for common tasks.
- Each js file should do one type of task. For instance, xdata.js should all functions to call backend. Similarly, we can have one js for defining all models, one js file for all business logic, one js file for all utility/common tasks, one js file for processing the backend -response.


This might take 3-4 iterations. So you can make a high level first iteration and then we can discuss.

**Comment by adityagp** [comment]
Would be good to have @wookhuk also providing some feedback on this. @eidehua will you be able to find time to work on this? It seems like it's a couple days work. Thanks!

**Comment by eidehua** [comment]
I can do work on this, but mainly on weekends. I think best approach is to first do the refactoring the javascript stuff first, before angularizing. Overall I think our javascript file serve their purposes, but some functions could be in the wrong file (as it could be a side purpose but not the main purpose).

**Comment by adityagp** [comment]
Got it. Do you think it can be done by the end of the month? One of us -- @siddta or @wookhuk or I may be able to help clean up if there's clear tasks that can be identified.

**Comment by eidehua** [comment]
Yes I think it can. I will first do a high level pass and then I can follow up with what else to do.

**Comment by wookhuk** [comment]
@eidehua I am angularizing and refactoring the frontend code in the "chi" files. It will have about 75% (my rough estimate) of the current functionality so it could be useful to take a look. We will eventually have to converge.

**Comment by adityagp** [comment]
@wookhuk do you think we should wait until you're done or should we proceed in parallel? 
@eidehua: fyi @wookhuk is trying to do a clean slate design for a user study.

**Comment by eidehua** [comment]
https://docs.google.com/a/illinois.edu/document/d/10YONgv1ayWDeK76SlRAzDR6cHV8C2CGhTqPVYn0sr8g/edit?usp=sharing

I have created a doc with the proposed updates, how should we proceed with this? Mostly look at the first pass things. 

Also send me emails for editing.

**Comment by adityagp** [comment]
I don't have access to this.

On Mon, Jun 13, 2016 at 4:00 AM, Ed <notifications@github.com> wrote:

>
> https://docs.google.com/a/illinois.edu/document/d/10YONgv1ayWDeK76SlRAzDR6cHV8C2CGhTqPVYn0sr8g/edit?usp=sharing
>
> I have created a doc with the proposed updates, how should we proceed with
> this? Mostly look at the first pass things.
>
> Also send me emails for editing.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zenvisage/zenvisage/issues/6#issuecomment-225525304>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABAfXaOw4ddMJLQVmAocGLxiESk9FIJ8ks5qLRwzgaJpZM4Ijtgm>
> .
>



-- 
Aditya Parameswaran
Assistant Professor, Illinois CS
http://data-people.cs.illinois.edu

**Comment by eidehua** [comment]
Added

**Comment by adityagp** [comment]
Done. Closing.
