### ISSUE TITLE
Clean-up the service and data packages at the back-end.

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#7]
Service package contains the code for Similarity, Representative, etc.
Data package contains the code for roaringdb executor. We need to have a well-defined interface so that classes service package need not be modified regardless of the underlying database.

--will add more details.

**Comment by siddta** [comment]
Couldn't get to it yet, will get started with this.

**Comment by adityagp** [comment]
Good idea. Please also loop me in once you figure out how to redesign this. And keep @seanzyx in the loop as well.

**Comment by siddta** [comment]
I have committed my changes needed for version 1 release. I'll like to focus on zql based  backend design now on for addding/redesigning the flow. For the main code, we should only add changes if needed for user study or data upload interface. 
@adityagp @wookhuk

**Comment by adityagp** [comment]
That sounds fine. Thanks for cleaning this up. 

I will take a quick look when I install and run @garyluoex's interface.
