### ISSUE TITLE
Clean up getInterfaceFormData, Representative, Outlier, Similarity to not use inmemorydatabase construction

### ISSUE THREAD

**Issue by superchaoran** [zenvisage/zenvisage#81]
Clean up getInterfaceFormData, Representative, Outlier, Similarity to not use inmemorydatabase construction.

**Comment by superchaoran** [comment]
https://github.com/zenvisage/zenvisage/commit/4a6a209cadc031cd48b5f4ed749c5077eec73210
Initial clean up done for:
Stripping off inmemorydatabase from analysis,outlier,representative,similarity and multiple corresponding placesin zvmain;can't strip off from PieceWiseAgrregation(PAA) which uses it in calc

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/21289209/f44b2e3a-c44b-11e6-9450-1a8aff3cff99.png)
following up clean up need to 
Revamp Executor to not use inmemorydatabase to construct;
Extract out inMemoryDatabase.getFormMetdaData() for all use cases;

**Comment by superchaoran** [comment]
Need revamp on PieceWiseAgrregation(PAA) which uses inMemoryDatabase in calc

**Comment by superchaoran** [comment]
Cleaning up unsued stack memory allocated for storing column data;

**Comment by superchaoran** [comment]
![image](https://cloud.githubusercontent.com/assets/7088689/22628387/ccabdc70-eb98-11e6-8178-ae772b5204fd.png)
![image](https://cloud.githubusercontent.com/assets/7088689/22628388/d2dd259a-eb98-11e6-8c43-ebccb146b781.png)
![image](https://cloud.githubusercontent.com/assets/7088689/22628390/dec3f78a-eb98-11e6-8ed9-f43c9e91dc45.png)
System now works with very large dataset. At least we can take in 680.6M flight dataset

**Comment by eidehua** [comment]
Great 👍
